### ISSUE TITLE
Fails to convert file

### ISSUE THREAD

**Issue by thomasheckmann** [semack/zx_tape_player#15]
**Describe the bug**
Fails to convert tzx file - found here: https://drive.google.com/file/d/1Bv2BFJwdTthvTk1CP_qhs-4GUAmQ6pxY/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by semack** [comment]
There is should be an unsupported type of block. I'll scheck

**Comment by semack** [comment]
fixed, there was a problem with incorrect handling of pause block.
