### ISSUE TITLE
The last iOS beta version expired

### ISSUE THREAD

**Issue by McKlaud76** [semack/zx_tape_player#25]
The latest beta version expired on TestFlight expired and the app is not available available any more to iOS users. 

Could you please rebuilt is and start redistributing as this app is really good and handy.

**Comment by semack** [comment]
will do, jus need to find a time for it.

**Comment by McKlaud76** [comment]
Thanks a lot.

**Comment by semack** [comment]
TestFligth has been updated. The app will be available for download after reviewing by Apple.

**Comment by silversmurfer** [comment]
Testfligt seems to have been updated again in the last 2 weeks - now getting a beta has expired message again

**Comment by semack** [comment]
I will update it when I get time this week.
