### ISSUE TITLE
unknown block type

### ISSUE THREAD

**Issue by thomasheckmann** [semack/zx_tape_player#5]
**Describe the bug**
Double Dash (1990)(Proxima)(48K-128K)(CZ)(en).tzx - has unknown block type (53)

**Comment by semack** [comment]
53 = 0x35
ID 35 - Custom info block
http://k1.spdns.de/Develop/Projects/zasm/Info/TZX%20format.html#CUSTOMBLOCK
@thomasheckmann  Could you explore what kind of data in the data block?

**Comment by semack** [comment]
fixed
