### ISSUE TITLE
If local file matched against ZXInfo - highlight file being played

### ISSUE THREAD

**Issue by thomasheckmann** [semack/zx_tape_player#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When a local file has been identified, this file should be "highlighted" in the list of files. Now it just shows the first in the list (which is probaly not the one being played)

**Describe alternatives you've considered**

**Additional context**
Use the md5/sha512 value returned from API (filecheck) to figure out which file is matched - and should be highlighted

**Comment by semack** [comment]
implemented
